### ISSUE TITLE
Research: identify physics formulas for airplane takeoff

### ISSUE THREAD

**Issue by nmkzzztos** [nmkzzztos/AeroDynamicsLab#1]
**Description:**

Conduct research to identify and document the key physics formulas involved in the airplane takeoff process. This includes factors such as thrust, lift, drag, and weight, and how they interact during takeoff.

**Define Key Variables:**

* Identify and document the primary forces: lift, drag, thrust, and weight.
* Outline the relationships between these forces during takeoff.

**Gather Physics Formulas:**

* Research formulas for lift (e.g., $L=\frac{1}{2}pv^2SC_L$)
* Research formulas for drag and thrust balance.
* Include Newton’s laws of motion as applicable to takeoff dynamics.

**Comment by Nikode-tec** [comment]
Definition der Schlüsselvariablen

1. Auftrieb (L):

Die nach oben gerichtete Kraft, die dem Gewicht entgegenwirkt und es dem Flugzeug ermöglicht, zu steigen.

2. Gewicht (W):

Die nach unten gerichtete Gravitationskraft, definiert als W=m ⋅ g

W=m⋅g, wobei:

m: Masse des Flugzeugs (in kg)
g: Erdbeschleunigung (~9,81m/s²).

3. Schub (T):

Die durch die Triebwerke erzeugte Vorwärtskraft, die das Flugzeug nach vorne beschleunigt.

4. Widerstand (D):

Die entgegen der Bewegungsrichtung wirkende Kraft aufgrund des Luftwiderstands.

**Comment by Nikode-tec** [comment]
**Zusammenhänge zwischen den Kräften während des Starts**


- Um den Start zu ermöglichen:
1. Der Schub muss den Widerstand überwinden: T>D.
2. Der Auftrieb muss das Gewicht überwinden: L>W.

Während des Startlaufs auf der Landebahn gilt:

- Der durch die Triebwerke erzeugte Schub erhöht die Geschwindigkeit (v).
- Eine erhöhte Geschwindigkeit verstärkt sowohl den Auftrieb als auch den Widerstand, da diese Kräfte von v²
  abhängen.

**Comment by Nikode-tec** [comment]
Wichtige physikalische Formeln

1. Auftriebskraft:

𝐿=1/2⋅𝜌⋅𝑣²⋅𝑆⋅𝐶𝐿
​
 
Dabei gilt:


ρ: Luftdichte (kg/m³).
v: Geschwindigkeit des Flugzeugs relativ zur Luft (m/s).
S: Flügelfläche (m²).
CL: Auftriebsbeiwert (dimensionslos), abhängig vom Anstellwinkel und der Flügelform.

**Comment by Nikode-tec** [comment]
**2. Widerstandskraft:**

D=1/2⋅ρ⋅v²⋅S⋅CD
​
 
Dabei gilt:
CD: Widerstandsbeiwert (dimensionslos), abhängig von der Form des Flugzeugs und den Strömungsbedingungen.



**3. Schub-Widerstand-Gleichgewicht:**

-Für eine gleichmäßige Beschleunigung:
T−D=m⋅a

Dabei gilt:

-T: Schub (N).
-D: Widerstand (N).
-a: Beschleunigung des Flugzeugs (m/s²).

Am Punkt des Abhebens gilt T>D.




**4. Newtons Zweites Gesetz der Bewegung (gilt für den Startlauf):**

F netto=m⋅a

Dabei gilt:

-F netto: Nettokraft, die auf das Flugzeug wirkt (Schub minus Widerstand und Rollwiderstand).

**Comment by Nikode-tec** [comment]
2. Widerstandskraft:

D=1/2⋅ρ⋅v²⋅S⋅CD
​

Dabei gilt:
CD: Widerstandsbeiwert (dimensionslos), abhängig von der Form des Flugzeugs und den Strömungsbedingungen.

3. Schub-Widerstand-Gleichgewicht:

- Für eine gleichmäßige Beschleunigung:
T−D=m⋅a

Dabei gilt:

- T: Schub (N).
- D: Widerstand (N).
- a: Beschleunigung des Flugzeugs (m/s²).

Am Punkt des Abhebens gilt T>D.

4. Newtons Zweites Gesetz der Bewegung (gilt für den Startlauf):

F netto=m⋅a

Dabei gilt:

- F netto: Nettokraft, die auf das Flugzeug wirkt (Schub minus Widerstand und Rollwiderstand).
